version: '3'
services:
  books_service_db:
    container_name: books_service_db
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: books_service_test
    ports:
    - "5432:5432"