version: "3"
services:
  books-service-postgres:
    container_name: books-service-postgres
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: books_service_test
    ports:
    - "5432:5432"
  # APP*****************************************
  books-service:
    build:
      dockerfile: dockerfile
      context: ../..
    container_name: books-service
    depends_on:
      - books-service-postgres
    environment:
      - "SPRING_PROFILES_ACTIVE=local,flyway"
      - "spring_datasource_url=jdbc:postgresql://localhost:5432/books_service_test"
    ports:
      - "8083:8083"
    network_mode: host
